In [14]:
import pandas as pd

from dsk.ml import transform
from dsk.ml.model import MLModel
from dsk.ml.step import (
    BinColumn,
    OHE_Columns,
    ReplaceNaNs,
    SelectColumns,
    StandardizeScaler,
    ClipColumn,
    OrdinalEncodeColumns,
)
from dsk.ml.transform import Sequential

In [15]:
# Create titanic data
Pclass = [1, 1, 3, 3, 1, 3, 3, 1, 3, 2]
Sex = ["m", "m", "f", "m", "f", "m", "m", "f", "m", "m"]
Age = [33.0, 28.0, 16.0, 44.0, 58.0, 20.0, 20.0, 18.0, 21.0, 54.0]
Survivied = [0, 0, 1, 1, 1, 0, 0, 1, 0, 0]

titanic_data = {"Pclass": Pclass, "Sex": Sex, "Age": Age, "Survivied": Survivied}

titanic_df = pd.DataFrame(titanic_data)

In [16]:
bin_col = OrdinalEncodeColumns(cols=["Age", "Sex"])

In [17]:
bin_col.fit_transform(titanic_df)

   Pclass  Sex  Age  Survivied
0       1    0    0          0
1       1    0    1          0
2       3    1    2          1
3       3    0    3          1
4       1    1    4          1
5       3    0    5          0
6       3    0    5          0
7       1    1    6          1
8       3    0    7          0
9       2    0    8          0

In [10]:
bin_col.inverse_transform(titanic_df)

   Pclass Sex      Age  Survivied
0       1   m  45.5000          0
1       1   m  26.5000          0
2       3   f  17.9995          1
3       3   m  45.5000          1
4       1   f  45.5000          1
5       3   m  17.9995          0
6       3   m  17.9995          0
7       1   f  17.9995          1
8       3   m  26.5000          0
9       2   m  45.5000          0