In [1]:
import pandas as pd

from dsk.ml import transform
from dsk.ml.model import MLModel
from dsk.ml.step import (
    BinColumn,
    OHE_Columns,
    ReplaceNaNs,
    SelectColumns,
    StandardizeScaler,
)
from dsk.ml.transform import Sequential

In [2]:
# Create titanic data
Pclass = [1, 1, 3, 3, 1, 3, 3, 1, 3, 2]
Sex = ["m", "m", "f", "m", "f", "m", "m", "f", "m", "m"]
Age = [33.0, 28.0, 16.0, 44.0, 58.0, 20.0, 20.0, 18.0, 21.0, 54.0]
Survivied = [0, 0, 1, 1, 1, 0, 0, 1, 0, 0]

titanic_data = {"Pclass": Pclass, "Sex": Sex, "Age": Age, "Survivied": Survivied}

titanic_df = pd.DataFrame(titanic_data)

In [ ]:
std_scaler = StandardizeScaler(
    col_in=["Age", "Pclass"],
    col_out=["Age_scaled", "Pclass scaled"],
    # col_in="Age", col_out="Age_scaled"
)

In [10]:
std_scaler.fit_transform(titanic_df)

   Pclass Sex   Age  Survivied  Age_scaled  Pclass scaled
0     1.0   m  33.0          0    0.115772      -1.106163
1     1.0   m  28.0          0   -0.205817      -1.106163
2     3.0   f  16.0          1   -0.977632       0.905042
3     3.0   m  44.0          1    0.823269       0.905042
4     1.0   f  58.0          1    1.723719      -1.106163
5     3.0   m  20.0          0   -0.720360       0.905042
6     3.0   m  20.0          0   -0.720360       0.905042
7     1.0   f  18.0          1   -0.848996      -1.106163
8     3.0   m  21.0          0   -0.656042       0.905042
9     2.0   m  54.0          0    1.466448      -0.100560

In [11]:
std_scaler.inverse_transform(titanic_df)

    Age
0  33.0
1  28.0
2  16.0
3  44.0
4  58.0
5  20.0
6  20.0
7  18.0
8  21.0
9  54.0